api/rda.py, web.py
Otherwise it returns: AttributeError: 'Babel' object has no attribute 'localeselector'
=> Use babel.init_app() instead of babel.localeslector decorator

api/digital_csic.py, api/dspace7.py, api/evaluator.py, api/example_plugin.py, config.ini.template, docs/index.md
=> Updated documentation and removed docstrings

api/digital_csic.py, api/epos.py, api/evaluator.py, api/rda.py, api/utils.py, config.ini.template, petition.py
Added the EPOS plugin and petition.py for easy use of the API
=> Added EPOS compatibility  

api/evaluator.py, api/utils.py, plugins/epos/config.ini, plugins/epos/plugin.py
Added validation for the UUID and licenses
=> Improved findabilty and reusability checks

api/evaluator.py, api/utils.py, fair.py, plugins/epos/config.ini, plugins/epos/plugin.py
Fixes:
- RDA-A1-01M to validate those metadata elements from `terms_access` that actually have values assigned
- RDA-A1-03D to incorporate Handle/DOI resolution using Handle Proxy Server
Resolves #90
=> Refactor RDA-A1-01M and RDA-A1-03D

api/evaluator.py, api/utils.py, fair.py, plugins/epos/config.ini, plugins/epos/plugin.py
Now the test cheks if the license is open mainly creative commons
After the general test it checks for a creative commons license , the logic being if the metadata provides a download URL and an open license it means that the data is open for download
A common license is "https://creativecommons.org/licenses/by-nc/4.0/" but in the file the software checks the licenses, its written as "https://creativecommons.org/licenses/by-nc/4.0/legalcode" so if the first try fails the program tries adding "legalname"
=> Updated test a1-01m

plugins/epos/config.ini, plugins/epos/plugin.py
The tests that require a specific parsing have been adapted into EPOS
=> Parsing tests

api/utils.py, plugins/epos/config.ini, plugins/epos/plugin.py
Test a1-03m is simple just checking if there is metadata
Test a1-03d looks for the doi and resolves it via www.doi.org API
=> Tests added a1-03

plugins/epos/config.ini, plugins/epos/plugin.py
Added config.ini links and corrected the tests
=> Modiffied the tests for manual data and metadata aquisition

plugins/epos/config.ini
Small mistake fixed becaause the names did  not match
The names in config.ini were not correct
=> Updated mistake in config.ini

plugins/epos/plugin.py
The function was fixed in a previus commit but somehow it vanished
=> Fix rda_i1_02m

.pre-commit-config.yaml, api/utils.py, plugins/digital_csic/plugin.py, plugins/dspace7/plugin.py, plugins/epos/plugin.py, plugins/example_plugin/plugin.py, plugins/gbif/plugin.py, plugins/signposting/plugin.py, pyproject.toml, scripts/petition.py, utils/pdf_gen.py, utils/smart_plugin.py
For the moment : 
Docstrings in the accesibility tests 
Petition.py
=> Small upgrades and fixes  

api/evaluator.py
=> Support for interoperability-related metadata terms

api/evaluator.py, plugins/epos/config.ini, plugins/epos/plugin.py
=> Updated i1_02d so now it checks that no data comes

api/evaluator.py, plugins/epos/config.ini, plugins/epos/plugin.py
Although not tested in a positive response
=> Test r1_2_01m added

api/utils.py, plugins/epos/plugin.py
Only for indicators implemented in EPOS plugin; we'll need eventually to cover all of them
=> Homogeneise <msg> property as a dict with a 'message' and 'points'

plugins/epos/plugin.py
Test corrected so it doesnt give points whwn it shouldnt
=> Corrected i3_02m

api/rda.py, fair.py
=> Obtain the list of available plugins dynamically

api/rda.py, docs/How  to use the epos plugin.md, fair-api.yaml, fair.py, plugins/digital_csic/config.ini, plugins/epos/config.ini, plugins/gbif/config.ini, scripts/fair-eva.py
Now the API can give a list of all the endpoints of the diferent plugins, or give a certain endpoint for an specific plugin
Related to issue #181
=> Added path /endpoint

plugins/epos/plugin.py
This helps with issue #188 and issue #190
=> Corrected non list msgs

docs/How  to use the epos plugin.md
=> Modified scores documentation

plugins/epos/plugin.py
Scores according to completion of `terms_access` metadata elements
=> New implementation of A1-01M

.pre-commit-config.yaml
Fixes https://github.com/PyCQA/docformatter/pull/287
=> Use docformatter to latest master version
